[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x", "openssl"]

[deploy]
startCommand = "npx prisma db push --accept-data-loss && npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
