[build]
builder = "nixpacks"
buildCommand = "npm ci && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma db push && npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "matable-rs"

[services.variables]
NODE_ENV = "production"
NEXTAUTH_URL = "https://matable.app"
