[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma db push --accept-data-loss; NODE_OPTIONS='--max-http-header-size=32768' npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
